// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job_scheduler.proto

package jobscheduler

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterReq struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RegisterRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WorkerID             string   `protobuf:"bytes,2,opt,name=workerID,proto3" json:"workerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRes) Reset()         { *m = RegisterRes{} }
func (m *RegisterRes) String() string { return proto.CompactTextString(m) }
func (*RegisterRes) ProtoMessage()    {}
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{1}
}

func (m *RegisterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRes.Unmarshal(m, b)
}
func (m *RegisterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRes.Marshal(b, m, deterministic)
}
func (m *RegisterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRes.Merge(m, src)
}
func (m *RegisterRes) XXX_Size() int {
	return xxx_messageInfo_RegisterRes.Size(m)
}
func (m *RegisterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRes.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRes proto.InternalMessageInfo

func (m *RegisterRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterRes) GetWorkerID() string {
	if m != nil {
		return m.WorkerID
	}
	return ""
}

type DeregisterReq struct {
	WorkerID             string   `protobuf:"bytes,1,opt,name=workerID,proto3" json:"workerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeregisterReq) Reset()         { *m = DeregisterReq{} }
func (m *DeregisterReq) String() string { return proto.CompactTextString(m) }
func (*DeregisterReq) ProtoMessage()    {}
func (*DeregisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{2}
}

func (m *DeregisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterReq.Unmarshal(m, b)
}
func (m *DeregisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterReq.Marshal(b, m, deterministic)
}
func (m *DeregisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterReq.Merge(m, src)
}
func (m *DeregisterReq) XXX_Size() int {
	return xxx_messageInfo_DeregisterReq.Size(m)
}
func (m *DeregisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterReq proto.InternalMessageInfo

func (m *DeregisterReq) GetWorkerID() string {
	if m != nil {
		return m.WorkerID
	}
	return ""
}

type DeregisterRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeregisterRes) Reset()         { *m = DeregisterRes{} }
func (m *DeregisterRes) String() string { return proto.CompactTextString(m) }
func (*DeregisterRes) ProtoMessage()    {}
func (*DeregisterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{3}
}

func (m *DeregisterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterRes.Unmarshal(m, b)
}
func (m *DeregisterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterRes.Marshal(b, m, deterministic)
}
func (m *DeregisterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterRes.Merge(m, src)
}
func (m *DeregisterRes) XXX_Size() int {
	return xxx_messageInfo_DeregisterRes.Size(m)
}
func (m *DeregisterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterRes proto.InternalMessageInfo

func (m *DeregisterRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type StartJobReq struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartJobReq) Reset()         { *m = StartJobReq{} }
func (m *StartJobReq) String() string { return proto.CompactTextString(m) }
func (*StartJobReq) ProtoMessage()    {}
func (*StartJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{4}
}

func (m *StartJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartJobReq.Unmarshal(m, b)
}
func (m *StartJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartJobReq.Marshal(b, m, deterministic)
}
func (m *StartJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartJobReq.Merge(m, src)
}
func (m *StartJobReq) XXX_Size() int {
	return xxx_messageInfo_StartJobReq.Size(m)
}
func (m *StartJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartJobReq proto.InternalMessageInfo

func (m *StartJobReq) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *StartJobReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type StartJobRes struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartJobRes) Reset()         { *m = StartJobRes{} }
func (m *StartJobRes) String() string { return proto.CompactTextString(m) }
func (*StartJobRes) ProtoMessage()    {}
func (*StartJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{5}
}

func (m *StartJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartJobRes.Unmarshal(m, b)
}
func (m *StartJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartJobRes.Marshal(b, m, deterministic)
}
func (m *StartJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartJobRes.Merge(m, src)
}
func (m *StartJobRes) XXX_Size() int {
	return xxx_messageInfo_StartJobRes.Size(m)
}
func (m *StartJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StartJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_StartJobRes proto.InternalMessageInfo

func (m *StartJobRes) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type StopJobReq struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopJobReq) Reset()         { *m = StopJobReq{} }
func (m *StopJobReq) String() string { return proto.CompactTextString(m) }
func (*StopJobReq) ProtoMessage()    {}
func (*StopJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{6}
}

func (m *StopJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopJobReq.Unmarshal(m, b)
}
func (m *StopJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopJobReq.Marshal(b, m, deterministic)
}
func (m *StopJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopJobReq.Merge(m, src)
}
func (m *StopJobReq) XXX_Size() int {
	return xxx_messageInfo_StopJobReq.Size(m)
}
func (m *StopJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StopJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_StopJobReq proto.InternalMessageInfo

func (m *StopJobReq) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type StopJobRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopJobRes) Reset()         { *m = StopJobRes{} }
func (m *StopJobRes) String() string { return proto.CompactTextString(m) }
func (*StopJobRes) ProtoMessage()    {}
func (*StopJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{7}
}

func (m *StopJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopJobRes.Unmarshal(m, b)
}
func (m *StopJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopJobRes.Marshal(b, m, deterministic)
}
func (m *StopJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopJobRes.Merge(m, src)
}
func (m *StopJobRes) XXX_Size() int {
	return xxx_messageInfo_StopJobRes.Size(m)
}
func (m *StopJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StopJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_StopJobRes proto.InternalMessageInfo

type QueryJobReq struct {
	JobID                string   `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryJobReq) Reset()         { *m = QueryJobReq{} }
func (m *QueryJobReq) String() string { return proto.CompactTextString(m) }
func (*QueryJobReq) ProtoMessage()    {}
func (*QueryJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{8}
}

func (m *QueryJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryJobReq.Unmarshal(m, b)
}
func (m *QueryJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryJobReq.Marshal(b, m, deterministic)
}
func (m *QueryJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryJobReq.Merge(m, src)
}
func (m *QueryJobReq) XXX_Size() int {
	return xxx_messageInfo_QueryJobReq.Size(m)
}
func (m *QueryJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryJobReq proto.InternalMessageInfo

func (m *QueryJobReq) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type QueryJobRes struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Error                bool     `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorText            string   `protobuf:"bytes,3,opt,name=errorText,proto3" json:"errorText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryJobRes) Reset()         { *m = QueryJobRes{} }
func (m *QueryJobRes) String() string { return proto.CompactTextString(m) }
func (*QueryJobRes) ProtoMessage()    {}
func (*QueryJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_94497fe360f3acc8, []int{9}
}

func (m *QueryJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryJobRes.Unmarshal(m, b)
}
func (m *QueryJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryJobRes.Marshal(b, m, deterministic)
}
func (m *QueryJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryJobRes.Merge(m, src)
}
func (m *QueryJobRes) XXX_Size() int {
	return xxx_messageInfo_QueryJobRes.Size(m)
}
func (m *QueryJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryJobRes proto.InternalMessageInfo

func (m *QueryJobRes) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *QueryJobRes) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *QueryJobRes) GetErrorText() string {
	if m != nil {
		return m.ErrorText
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "jobscheduler.RegisterReq")
	proto.RegisterType((*RegisterRes)(nil), "jobscheduler.RegisterRes")
	proto.RegisterType((*DeregisterReq)(nil), "jobscheduler.DeregisterReq")
	proto.RegisterType((*DeregisterRes)(nil), "jobscheduler.DeregisterRes")
	proto.RegisterType((*StartJobReq)(nil), "jobscheduler.StartJobReq")
	proto.RegisterType((*StartJobRes)(nil), "jobscheduler.StartJobRes")
	proto.RegisterType((*StopJobReq)(nil), "jobscheduler.StopJobReq")
	proto.RegisterType((*StopJobRes)(nil), "jobscheduler.StopJobRes")
	proto.RegisterType((*QueryJobReq)(nil), "jobscheduler.QueryJobReq")
	proto.RegisterType((*QueryJobRes)(nil), "jobscheduler.QueryJobRes")
}

func init() { proto.RegisterFile("job_scheduler.proto", fileDescriptor_94497fe360f3acc8) }

var fileDescriptor_94497fe360f3acc8 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcb, 0x4e, 0xe3, 0x30,
	0x14, 0x6d, 0xe6, 0xd1, 0xa6, 0xb7, 0x9d, 0xd1, 0xc8, 0x83, 0x44, 0x08, 0x08, 0x21, 0xb3, 0x00,
	0x84, 0x94, 0x45, 0x59, 0x76, 0x81, 0x14, 0xba, 0x80, 0x2e, 0x50, 0x49, 0x40, 0x2c, 0x51, 0x1e,
	0x56, 0x1f, 0xb4, 0x75, 0xb1, 0xdd, 0x02, 0x1f, 0xc4, 0x07, 0xf1, 0x47, 0x28, 0xae, 0x9d, 0x3a,
	0x11, 0xe9, 0xce, 0x27, 0xf7, 0xdc, 0x73, 0xcf, 0xcd, 0xb1, 0xe1, 0xff, 0x84, 0xc6, 0x4f, 0x3c,
	0x19, 0x91, 0x74, 0x39, 0x25, 0xcc, 0x5b, 0x30, 0x2a, 0x28, 0x6a, 0x4f, 0x68, 0x9c, 0x7f, 0xc3,
	0x27, 0xd0, 0x0a, 0xc8, 0x70, 0xcc, 0x05, 0x61, 0x01, 0x79, 0x41, 0x0e, 0x34, 0xa2, 0x34, 0x65,
	0x84, 0x73, 0xc7, 0x3a, 0xb2, 0x4e, 0x9b, 0x81, 0x86, 0xf8, 0xca, 0x24, 0xf2, 0x8c, 0xc8, 0x97,
	0x49, 0xa2, 0x89, 0x76, 0xa0, 0x21, 0x72, 0xc1, 0x7e, 0xa5, 0xec, 0x99, 0xb0, 0x9b, 0x9e, 0xf3,
	0x43, 0x6a, 0xe4, 0x18, 0x9f, 0xc3, 0x9f, 0x1e, 0x61, 0xc6, 0x3c, 0x93, 0x6c, 0x95, 0xc8, 0x67,
	0x45, 0xf2, 0x96, 0x99, 0xb8, 0x0b, 0xad, 0x50, 0x44, 0x4c, 0xf4, 0x69, 0xac, 0xb6, 0x48, 0xe8,
	0x6c, 0x16, 0xcd, 0x53, 0xbd, 0x85, 0x82, 0x08, 0xc1, 0xaf, 0x45, 0x24, 0x46, 0xca, 0x98, 0x3c,
	0xe3, 0x63, 0xb3, 0x99, 0xa3, 0x1d, 0xf8, 0x3d, 0xa1, 0x71, 0xee, 0x67, 0x0d, 0x30, 0x06, 0x08,
	0x05, 0x5d, 0xa8, 0x01, 0xdf, 0x73, 0xda, 0x06, 0x87, 0x67, 0xb2, 0x77, 0x4b, 0xc2, 0xde, 0xb7,
	0xb6, 0x3c, 0x98, 0x24, 0x9e, 0xd9, 0x4b, 0xe9, 0x9c, 0xa8, 0xf5, 0xe4, 0x39, 0x6b, 0x24, 0x8c,
	0x51, 0x26, 0x3d, 0xdb, 0xc1, 0x1a, 0xa0, 0x03, 0x68, 0xca, 0xc3, 0x3d, 0x79, 0x13, 0xce, 0x4f,
	0x29, 0xb9, 0xf9, 0xd0, 0xf9, 0xb0, 0xa0, 0x19, 0xea, 0x8c, 0xd1, 0x35, 0xfc, 0xd5, 0xd1, 0x3d,
	0xca, 0x9f, 0x8b, 0xf6, 0x3c, 0xf3, 0x12, 0x78, 0xc6, 0x0d, 0x70, 0x2b, 0x4b, 0x1c, 0xd7, 0xd0,
	0x2d, 0xfc, 0xdb, 0x44, 0xa2, 0xb4, 0xf6, 0x8b, 0x0d, 0x85, 0x7c, 0xdd, 0x2d, 0x45, 0x8e, 0x6b,
	0x9d, 0x4f, 0x0b, 0xea, 0x4a, 0xc6, 0x07, 0x5b, 0xa7, 0x50, 0xb6, 0x67, 0x44, 0xeb, 0x56, 0x96,
	0x32, 0x7b, 0x97, 0xd0, 0x50, 0x01, 0x20, 0xa7, 0xcc, 0xd3, 0xd9, 0xb9, 0x55, 0x95, 0x4c, 0xc0,
	0x07, 0x5b, 0xc7, 0x51, 0x36, 0x61, 0x64, 0xe9, 0x56, 0x96, 0x38, 0xae, 0xf9, 0x5d, 0x38, 0x4c,
	0xe8, 0xcc, 0x1b, 0xb2, 0x68, 0x35, 0x16, 0x91, 0x18, 0xd3, 0x79, 0x34, 0x2d, 0xf0, 0xfd, 0xdd,
	0x3e, 0x8d, 0xf3, 0x74, 0x42, 0xc2, 0x56, 0x84, 0x0d, 0xb2, 0xa7, 0x39, 0xb0, 0xe2, 0xba, 0x7c,
	0xa3, 0x17, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x09, 0x05, 0xb1, 0x0e, 0xba, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulerClient interface {
	RegisterWorker(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
	DeregisterWorker(ctx context.Context, in *DeregisterReq, opts ...grpc.CallOption) (*DeregisterRes, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) RegisterWorker(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	out := new(RegisterRes)
	err := c.cc.Invoke(ctx, "/jobscheduler.Scheduler/RegisterWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) DeregisterWorker(ctx context.Context, in *DeregisterReq, opts ...grpc.CallOption) (*DeregisterRes, error) {
	out := new(DeregisterRes)
	err := c.cc.Invoke(ctx, "/jobscheduler.Scheduler/DeregisterWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
type SchedulerServer interface {
	RegisterWorker(context.Context, *RegisterReq) (*RegisterRes, error)
	DeregisterWorker(context.Context, *DeregisterReq) (*DeregisterRes, error)
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobscheduler.Scheduler/RegisterWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).RegisterWorker(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_DeregisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).DeregisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobscheduler.Scheduler/DeregisterWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).DeregisterWorker(ctx, req.(*DeregisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jobscheduler.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _Scheduler_RegisterWorker_Handler,
		},
		{
			MethodName: "DeregisterWorker",
			Handler:    _Scheduler_DeregisterWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_scheduler.proto",
}

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	StartJob(ctx context.Context, in *StartJobReq, opts ...grpc.CallOption) (*StartJobRes, error)
	StopJob(ctx context.Context, in *StopJobReq, opts ...grpc.CallOption) (*StopJobRes, error)
	QueryJob(ctx context.Context, in *QueryJobReq, opts ...grpc.CallOption) (*QueryJobRes, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) StartJob(ctx context.Context, in *StartJobReq, opts ...grpc.CallOption) (*StartJobRes, error) {
	out := new(StartJobRes)
	err := c.cc.Invoke(ctx, "/jobscheduler.Worker/StartJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) StopJob(ctx context.Context, in *StopJobReq, opts ...grpc.CallOption) (*StopJobRes, error) {
	out := new(StopJobRes)
	err := c.cc.Invoke(ctx, "/jobscheduler.Worker/StopJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) QueryJob(ctx context.Context, in *QueryJobReq, opts ...grpc.CallOption) (*QueryJobRes, error) {
	out := new(QueryJobRes)
	err := c.cc.Invoke(ctx, "/jobscheduler.Worker/QueryJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	StartJob(context.Context, *StartJobReq) (*StartJobRes, error)
	StopJob(context.Context, *StopJobReq) (*StopJobRes, error)
	QueryJob(context.Context, *QueryJobReq) (*QueryJobRes, error)
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobscheduler.Worker/StartJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).StartJob(ctx, req.(*StartJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobscheduler.Worker/StopJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).StopJob(ctx, req.(*StopJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_QueryJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).QueryJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobscheduler.Worker/QueryJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).QueryJob(ctx, req.(*QueryJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jobscheduler.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJob",
			Handler:    _Worker_StartJob_Handler,
		},
		{
			MethodName: "StopJob",
			Handler:    _Worker_StopJob_Handler,
		},
		{
			MethodName: "QueryJob",
			Handler:    _Worker_QueryJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_scheduler.proto",
}
